import { readdir, readFile, writeFile } from "fs/promises";
import { join } from "path";

const contentDir = join(import.meta.dir, "../public/content");
const outFile = join(import.meta.dir, "generated-edges.ts");

const files = await readdir(contentDir);
const seen = new Set<string>();
const edges: { from: string; to: string }[] = [];

for (const file of files) {
  if (!file.endsWith(".md")) continue;
  const id = file.replace(/\.md$/, "");
  const text = await readFile(join(contentDir, file), "utf-8");

  const match = text.match(/## Related projects\n([\s\S]*?)(?=\n## |\n$|$)/);
  if (!match) continue;

  const section = match[1]!;
  const linkPattern = /\[([^\]]+)\]\(\/([^)]+)\)/g;
  let linkMatch;
  while ((linkMatch = linkPattern.exec(section)) !== null) {
    const target = linkMatch[2]!;
    const key = [id, target].sort().join("|");
    if (!seen.has(key)) {
      seen.add(key);
      const sorted = [id, target].sort();
      edges.push({ from: sorted[0]!, to: sorted[1]! });
    }
  }
}

edges.sort((a, b) => a.from.localeCompare(b.from) || a.to.localeCompare(b.to));

const lines = edges.map((e) => `  { from: "${e.from}", to: "${e.to}" },`).join("\n");
const content = `// Auto-generated by gen-edges.ts - do not edit\nexport const relatedEdges: { from: string; to: string }[] = [\n${lines}\n];\n`;

await writeFile(outFile, content);
console.log(`wrote ${edges.length} edges to ${outFile}`);
